### ISSUE TITLE
Drop down menu glitches

### ISSUE THREAD

**Issue by djtsorrell** [paullinuxthemer/Prof-Gnome#17]
I have noticed on some drop down menus that the text turns black when my mouse is not on the current option. Is this intentional? Also, in Nautilus, I have noticed a small glitch in the Home drop down menu. Images below. Using Pop_OS 20.04.

## Text turns black on drop down menu
![prof-gnome-glitch](https://user-images.githubusercontent.com/45468834/96844428-671b2d80-1447-11eb-88f4-a1d357d63a98.png)

## Graphical glitch in Nautilus
![Screenshot from 2020-10-22 09-03-18](https://user-images.githubusercontent.com/45468834/96844378-59fe3e80-1447-11eb-9bb8-a3788e795b58.png)

**Comment by andreiromila** [comment]
Hi, I cannot reproduce the glitch in Nautilus but you can fix the dropdown by adding the following code at the end of the gnome-shell.css file (.themes/_Prof-Gnome-Dark-3.5_/gnome-shell/gnome-shell.css)

```css

/**
 * Add at the end of gnome-shell.css file
 */
.popup-menu-item:checked {
  /*------------> Checked menu's*/
  color: #ffffff;
}

.popup-sub-menu .popup-menu-item.selected {
  background-color: #15539e;
  /*#3a3a3a;-------------------->Heading of submenu checked*/
  box-shadow: none;
  border-radius: 4.66px;
  color: #ffffff;
}
```

Before:
![gnome-shell_before](https://user-images.githubusercontent.com/26268517/97114249-bdaa9500-16ef-11eb-86e8-d1fbb896479c.png)

After:
![gnome-shell_after](https://user-images.githubusercontent.com/26268517/97114256-c26f4900-16ef-11eb-89a9-0594905f69b3.png)

Hope it is helpful!
