### ISSUE TITLE
Version 3.5 some title bars very big

### ISSUE THREAD

**Issue by Etamuk** [paullinuxthemer/Prof-Gnome#6]
Hello,
at first:
thank you for sharing your hard work! Great job!

Since I updated from version 3.4 zo 3.5 some title bars are bigger now. 
I noticed this for Telegram desktop app and SoftMaker Office-Apps.
Please see my screenshots.

Telegram main window (prof-gnome version 3.4, version 3.5 below)
![Bildschirmfoto von 2020-05-13 20-23-49](https://user-images.githubusercontent.com/20098065/81850599-7e7cf300-9558-11ea-9bd1-ac43aa80a3a6.png)
![Bildschirmfoto von 2020-05-13 20-25-54](https://user-images.githubusercontent.com/20098065/81850603-7f158980-9558-11ea-862a-ff863e4553ee.png)

Settings window of SoftMaker Office (prof-gnome version 3.4, version 3.5 below)
![Bildschirmfoto von 2020-05-13 20-24-28](https://user-images.githubusercontent.com/20098065/81850749-b84df980-9558-11ea-8ef5-fcd921ffb87d.png)
![Bildschirmfoto von 2020-05-13 20-25-28](https://user-images.githubusercontent.com/20098065/81850753-b84df980-9558-11ea-888c-f38fe236b1fe.png)
This happens to all SoftMaker windows, I picked this window as example cause its smaller.

Kind regards from Germany

**Comment by paullinuxthemer** [comment]
I installed both telegram and softmaker. I can not reproduce your problem. What DE,gnome version, distro are you running?

**Comment by Etamuk** [comment]
I am using Fedora 32 (Workstation Edition) with Gnome 3.36.2, Wayland window manager.
My screen is a 4K screen with 3840x2160 pixel. Maybe that´s the problem?

**Comment by murat-cileli** [comment]
Hello. I can confirm this with Gnome 3.36, 4K screen and 200% scaling.

**Comment by paullinuxthemer** [comment]
This theme uses REM instead of pixels on certain elements.  This conflict with the 200 percent scaling. I have no 4k monitor to test on

**Comment by paullinuxthemer** [comment]
Maybe het scaling at 110 percent and use 12pixel font?

**Comment by paullinuxthemer** [comment]
The theme is actually designed for low res to HD.

**Comment by Etamuk** [comment]
Scaling to 110% and 12px font is not really nice. Its to small for me. 
No problem. Nevertheless it´s a wonderful theme :-)

**Comment by murat-cileli** [comment]
3.4.1 version is OK. I will stick with this. And of course it's a wonderful theme. :) Thank you.

**Comment by andreiromila** [comment]
I absolutely love this theme and wanted to minimize the size of the windows but also the radius which was a bit much too.
This is not happening with gnome native applications like "Files", "Tweaks" or "Calculator" but it does with Gimp, VLC, Postman etc...

I added the following code at the end of the gtk.css file (in gtk3.0 folder), and restarted (Alt + F2 then "r" and Enter): 
```css
/**
 * Some Tweaks for 4k Monitors (200% scale)
 */
 headerbar.default-decoration,
 .csd headerbar.default-decoration,
 headerbar.default-decoration:backdrop,
 .csd headerbar.default-decoration:backdrop,
 .default-decoration.titlebar:not(headerbar),
 .csd .default-decoration.titlebar:not(headerbar),
 .default-decoration.titlebar:backdrop:not(headerbar),
 .csd .default-decoration.titlebar:backdrop:not(headerbar) {
     /** Application Header size */
     /*  min-height: 1.7875rem; */
     min-height: 1.2rem;
 }
 
 .background .titlebar {
     /* Border Radius */
     /*border-top-left-radius: 0.4125rem;8px;*/
     /*border-top-right-radius: 0.4125rem;8px;*/
     border-top-left-radius : 8px;
     border-top-right-radius: 8px;
 }
 
 decoration {
     /* Radius for no Gnome Windows */
     /* border-radius: 0.4125rem 0.4125rem 0 0; */
     border-radius: 8px 8px 0 0;
 }
```

Results (before): 
![Before_Theme](https://user-images.githubusercontent.com/26268517/97101533-a1323c80-169e-11eb-907e-f7f5d1961420.png)

After:
![After_Theme](https://user-images.githubusercontent.com/26268517/97101535-a8594a80-169e-11eb-8744-44ac489ef781.png)

Hope it is helpful.
